### ISSUE TITLE
G Keybinding cannot be use by other mods, hardcoded in src/main/java/net/drpcore/client/keybinding/DRPCoreKeybindings.java

### ISSUE THREAD

**Issue by enricotagliavini** [DarkRoleplay/Dark-Roleplay-Core#1]
Description:

when Dark Roleplay Core mod is install the G keybinding cannot be used for other mods. When G is pressed an orange text in the top center of the screen will appear "This is a Test". Also such keybinding doesn't appear in the control options and cannot be changed to remove the conflict, which is not even shown. According to controls the G key is free for use by other mods.

The line printing the text is in file src/main/java/net/drpcore/client/keybinding/DRPCoreKeybindings.java , since there is no use for the G keybinding at the moment one quick solution is to comment out the last elif until needed. switchArmor.isKeyDown() returns true if the key is pressed even if the keybiding is not registered, so commenting out the registration only is not enough.

I noticed because the G binding is used by default by Ender IO to enable / disable gliding and with this mod installed I must change the Enter IO key for gliding to use it.

I'm using forge 1.10.2-12.18.2.2151

**Comment by JTK222** [comment]
mh.... sorry forgot about that one :/
Working on a major rework of the Core Mod because the code got messy but might fix that one maybe tomorrow when I have time. And I haven't known that this will block other Mods receiving this key Event :O
Oh and might I get your Minecraft Name? Cause I am planing a credits list with everybody that helped me finding Bugs and co. as people doing this got rare :(

**Comment by enricotagliavini** [comment]
No worries, thank you for your work on the mod and for the quick reply. Maintaining a mod is a huge work and given the rate at which Minecraft changes plus it was not even designed to be mod-able at the beginning, I understand this is no easy task :)

My Minecraft name is IcoSauro

**Comment by JTK222** [comment]
might take a little bit more Time.... noticed just now that I comitted to the wrong Branch and need first to fix a few things up....

**Comment by JTK222** [comment]
Ok... I am really sorry but I cant fix it.... getting an error every time I try to revert the changes on Github :/
But the re-code should fix this issue even when it might take some time.

**Comment by enricotagliavini** [comment]
That's ok, at least there is a workaround. I'm definitely looking forward
for the recoded version, feel free to ping me when it's out. If I'm still
playing MC (and come and go and then come back again, you know) I'll try it
with pleasure.

If you are getting git errors (you say you get errors when you try to
revert a change on github) I might be able to help. I use git for work, I'm
not a ninja guru maybe, but I know something about it.

I might also try to fix this by myself, I never tried to build a Minecraft
mod, not sure how fast you get frustrated by it.
