### ISSUE TITLE
NPE Crash

### ISSUE THREAD

**Issue by WenXin20** [DarkRoleplay/Dark-Roleplay-Core#6]
I crash as soon as I entered my world. I am using Dark Roleplay Core v0.3.5d, Medieval v0.2.4b, and forge 1.12.2-v14.23.2.2613.

https://pastebin.com/mtSqvxAx

**Comment by JTK222** [comment]
Could you post the fml-client-latest.log?
The Crashlog doesn't contain everything that I could use (it doesn't even contain an error caused by my mod)

**Comment by JTK222** [comment]
Ok found a... kind of solution?
At least for your problem. Though this error shouldn't happen.
So It would be nice if you could also post the fml-client-latest.log
The Current Fix is waiting for approval on Curse.

**Comment by WenXin20** [comment]
It works now, thanks! The fml-client-latest.log didn't save, so is there a way for me to get the previous mod file again to get the log?

**Comment by JTK222** [comment]
Nah, then nevermind. If there is a bigger issue behind this then someone is going to report it in the future xD #lazyDev
Going to close this now.
